const statusColors = { Completed: 'green', Preparing: 'orange', Pending: 'purple', Cancelled: 'red', Ready: 'green', Served: 'green' }

export default function Dashboard({ onNew, orders = [], tables = [] }) {
    const sales = orders.reduce((sum, order) => sum + Number(order.amount || 0), 0)
    const pending = orders.filter((order) => ['Pending', 'Preparing', 'Ready'].includes(order.status)).length
    const occupied = tables.filter((table) => table.status === 'occupied' || table.status === 'payment_pending').length
    const average = orders.length ? sales / orders.length : 0
    const statusCounts = orders.reduce((result, order) => ({ ...result, [order.status]: (result[order.status] || 0) + 1 }), {})
    const summary = Object.entries(statusCounts).slice(0, 4)
    return <div className="page-grid"><div className="dashboard-head"><div><h2>Overview</h2><p>Live performance from your restaurant data.</p></div><button className="primary" onClick={onNew}>＋ New Order</button></div><div className="stats">{[['Today’s Sales', `₹${sales.toLocaleString('en-IN')}`, `${orders.length} orders`], ['Today’s Orders', `${orders.length}`, 'From Supabase'], ['Pending Orders', `${pending}`, pending ? 'Needs attention' : 'All clear'], ['Tables Occupied', `${occupied} / ${tables.length}`, tables.length ? `${Math.round((occupied / tables.length) * 100)}% capacity` : 'No tables'], ['Avg. Order Value', `₹${Math.round(average).toLocaleString('en-IN')}`, 'Live average']].map(([label, value, detail]) => <div className="stat" key={label}><div className="stat-top"><span>{label}</span><span className="stat-icon">◈</span></div><h3>{value}</h3><span className={detail === 'Needs attention' ? 'badge orange' : 'up'}>{detail}</span></div>)}</div><div className="grid-two"><section className="panel"><div className="panel-head"><h3>Order status</h3><span className="muted">{orders.length} total</span></div>{summary.length ? summary.map(([name, count]) => <div key={name} style={{ marginBottom: 14 }}><div className="summary-row"><span className="summary-label"><i className={`dot ${statusColors[name] || 'purple'}`}></i>{name}</span><b>{count}</b></div><div className="progress"><i style={{ width: `${Math.min(100, (count / orders.length) * 100)}%` }}></i></div></div>) : <p className="empty-state muted">No orders recorded yet.</p>}</section><section className="panel"><div className="panel-head"><h3>Service snapshot</h3><span className="muted">Live data</span></div><div className="dashboard-snapshot"><strong>{pending ? `${pending} orders need attention` : 'Service is clear'}</strong><span>{occupied} occupied tables</span><span>{orders.filter((order) => order.payment !== 'Pending').length} paid orders</span></div></section></div><section className="panel"><div className="panel-head"><h3>Recent Orders</h3><span className="muted">{orders.length} records</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>ORDER ID</th><th>TABLE</th><th>CUSTOMER</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{orders.slice(0, 8).map((order) => <tr key={order.id}><td>{order.id}</td><td>{order.table}</td><td>{order.customer}</td><td>₹{Number(order.amount).toLocaleString('en-IN')}</td><td><span className="badge green">{order.status}</span></td></tr>)}</tbody></table>{!orders.length && <p className="empty-state muted">Orders will appear here after they are sent to KOT.</p>}</div></section></div>
}
