import { useState } from 'react'

const filters = ['All', 'Pending', 'Preparing', 'Ready', 'Served', 'Completed', 'Cancelled']

export default function Orders({ orders = [], onExport, onShowBill, onCancel, onRefund }) {
    const [filter, setFilter] = useState('All')
    const visibleOrders = filter === 'All' ? orders : orders.filter((order) => order.status === filter)
    return <div className="page-grid"><div className="panel-head"><div><h2 className="section-title">Order history</h2><p className="crumb">Live orders loaded from Supabase</p></div><button className="primary" onClick={onExport} disabled={!orders.length}>Export CSV</button></div><div className="filters">{filters.map((item) => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}{item === 'All' ? ` · ${orders.length}` : ` · ${orders.filter((order) => order.status === item).length}`}</button>)}</div><section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>ORDER ID</th><th>TABLE</th><th>CUSTOMER</th><th>AMOUNT</th><th>PAYMENT</th><th>STATUS</th><th>TIME</th><th>ACTIONS</th></tr></thead><tbody>{visibleOrders.map((order) => <tr key={order.id}><td><b>{order.id}</b></td><td>{order.table}</td><td>{order.customer}</td><td>₹{Number(order.amount).toLocaleString('en-IN')}</td><td>{order.payment}</td><td><span className={`badge ${order.status === 'Cancelled' ? 'red' : order.payment === 'Refunded' ? 'orange' : 'green'}`}>{order.status}</span></td><td>{order.time}</td><td><div className="order-actions">{order.payment !== 'Pending' && order.payment !== 'Refunded' && <button className="secondary" onClick={() => onShowBill(order)}>View bill</button>}{!['Completed', 'Cancelled'].includes(order.status) && <button className="secondary" onClick={() => onCancel(order)}>Cancel</button>}{order.payment !== 'Pending' && order.payment !== 'Refunded' && <button className="danger-button" onClick={() => onRefund(order)}>Refund</button>}</div></td></tr>)}</tbody></table>{!visibleOrders.length && <p className="empty-state muted">No {filter === 'All' ? '' : `${filter.toLowerCase()} `}orders found.</p>}</div></section></div>
}
